apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-devops-deployment
  labels:
    app: eks-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-devops
  template:
    metadata:
      labels:
        app: eks-devops
    spec:
      containers:
        - name: eks-devops
          # original_image_container_path: ghcr.io/stacksimplify/kube-nginxapp1:1.0.0 (FOR TESTING OR PRE-REQUISITE CHECKS)
          image: 820825185444.dkr.ecr.ap-northeast-2.amazonaws.com/aws-eks-devops-test:1.0
          ports:
            - containerPort: 80
